---
- name: Install and configure Nginx
  hosts: all  # Replace with your target hosts or group name
  become: yes
  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: present

   #- name: Copy application code
     # copy:
      #  src: /path/to/your/app
      # dest: /var/www/html/

    - name: Start Nginx service
      service:
        name: nginx
        state: started

    - name: Enable Nginx service at boot
      service:
        name: nginx
        enabled: yes
